#ifndef __BFC_DEF_H_
#define __BFC_DEF_H_

/**
	* BFC.EXE Message List
*/
const char *noInputFile = "BFC.EXE: Invalid command! No input file.\nPlease try again!\nUse switch -h to view HELP.\n";
const char *invalidCommand = "BFC.EXE: Invalid command!\nPlease try again!\nUse switch -h to view HELP.\n";
const char *inputFileNotFound = "BFC.EXE: Error! Input file not found.\nPlease try again!\nUse switch -h to view HELP.\n";
const char *inputFileAccessError = "BFC.EXE: Input file access error!\n";
const char *compileCompilerFailed = "Compilation of compiler failed!\n";
const char *resourceAlreadyCompiled = "BFC.EXE: Error!\nResource already compiled!\nUse switch -h to view HELP.\n";
const char *errorsFound = "BFC.EXE: Errors found! Compilation terminated.";
const char *invalidFileExt = "BFC.EXE: Invalid file extension!\nFile must end with .bf or .BF\n";
const char *helpFile = "OVERVIEW: bfc BF compiler\n\n\
USAGE: bfc.exe [options] <input file>\n\n\
OPTIONS: \
\n\t-h\t\tView this help file then exit. \
\n\t-x32\t\tCompile a x86-x32 binary. \
\n\t\t\t\tThis is the default compiler binary. \
\n\t-x64\t\tCompile a x86-x64 binary. \
\n\t\t\t\tOverrides with -x32 switch. \
\n\t-o\t\tCompile the source file.\n";

/**
	* Sub Compiler switches
*/
const char * object_switch = "-o";
const char * include_switch = "-I";
const char * lib_switch = "-L";
const char * help_switch = "--help";
const char * static_lib = "-static";

/** 
	* Configuration Fields
*/
const char *compiler_x32 = "compiler_32";
const char *compiler_x64 = "compiler_64";
const char *compiler_folder = "compiler_folder";
const char *compiler_executable = "compiler_exec";
const char *tmpfolder = "tmp";
const char *source_ext = "source_ext";
const char *compiler_name = "compiler";

/** 
	* Source control
*/
const char *includes_comment = "/* This source file is generated by using bfc.exe\n All Rights Reserved... */\n";
const char *includes = "#include <stdio.h>\n\n";
const char *mainFunctionTop = "int\nmain (void)\n{\n";
const char *mainArray = "\tchar mainArray [1024] = {\"\\0\"};\n";
const char *mainPointer = "\tint point = 0;\n\n";
const char *incPointer = "\tpoint++;\n";
const char *decPointer = "\tpoint--;\n";
const char *incValue = "\tmainArray[point]++;\n";
const char *decValue = "\tmainArray[point]--;\n";
const char *print = "\tputchar (mainArray[point]);\n";
const char *get = "\tmainArray[point] = getchar();\n";
const char *openWhile = "\twhile (mainArray[point] != 0) {\n";
const char *closeWhile = "\t}\n";
const char *mainReturn = "\treturn (0);\n";
const char *mainFunctionBottom = "}";

#endif /* __BFC_DEF_H_ */
